import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import LoginBtn from './LoginBtn';
import LogOutBtn from './LogOutBtn'; 
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import {getServerSession} from "next-auth"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session =await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar"> 
        <Link href="/" className="logo">Appleforum</Link> 
        <Link href="/list">List</Link> 
       {/*  { 
          session 
            ? <span>{session.user.name} <LogOutBtn/> </span> 
            : <LoginBtn />
        }  */}
        <LoginBtn></LoginBtn>
       {/*  <LogOutBtn/> */}
      </div>  
       {children}
      </body>
    </html>
  )
}
